devtools::install_github("gluc/ahp", build_vignettes = FALSE)
install.packages("data.tree")
install.packages("formattable")
install.packages("DiagrammeR")
install.packages("readr")
library(ahp)
library(data.tree)
library(formattable)
library(DiagrammeR)
library(readr)
setwd("C:/Users/klism/Documents/GitHub/APU/lab2/")
ahpFile <- system.file("extdata", "lodowki.ahp", package="ahp")
ahp <- Load(ahpFile)
ahpData <- Load("lodowki.ahp")
Visualize(ahpData)
print(ahpData, filterFun = isNotLeaf)
Calculate(ahpData)
Analyze(ahpData)
AnalyzeTable(ahpData)
ahp::RunGUI()
